### ISSUE TITLE
Shut off AppVeyor

### ISSUE THREAD

**Issue by MSP-Greg** [MSP-Greg/reline#1]
@aycabta

If you have access rights to AppVeyor, I can help with shutting it off...

**Comment by aycabta** [comment]
I had @hsbt remove ruby/reline from AppVeyor list a while ago. Thank you!

**Comment by aycabta** [comment]
[ruby/reline#129](https://github.com/ruby/reline/pull/129)
Passed without AppVeyor.

**Comment by MSP-Greg** [comment]
Thanks.  I hate false red 'X's
